name:       coursework
version:    0.1.0.0
github:     "AndyKaspe07/comp2212"
license:    BSD-3-Clause
authors:     "Anderson Kaspe, Harry Vinall & Alexis Shiacolas"
maintainer: "example@example.com"
copyright:  "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: Alex and Happy project.

dependencies:
- base >= 4.7 && < 5
- array
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Interpreter
    - CSVParser
    - Parser
    - Lexer
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  parseCSV-exe:
    main: ParserMain.hs
    source-dirs: app/CSVParser
    dependencies:
      - coursework
  main-exe:
    main: Main.hs
    source-dirs: app/Main
    dependencies:
      - coursework

tests:
  coursework-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coursework
